#!/bin/sh

COMMAND=$1
shift

case $COMMAND in
  export:env)
    PASSPHRASE=$(cat passphrase)
    echo $PASSPHRASE
    if [[ -z $PASSPHRASE ]]; then
      echo "No passphrase"
      exit 1
    fi
    gpg --batch --yes --symmetric --cipher-algo AES256 --passphrase=$PASSPHRASE env/.env
    ;;
  import:env)
    PASSPHRASE=$(cat passphrase)
    echo $PASSPHRASE
    if [[ -z $PASSPHRASE ]]; then
      echo "No passphrase"
      exit 1
    fi
    gpg --batch --yes --decrypt --passphrase=$PASSPHRASE --output env/.env env/.env.gpg
    ;;
  *)
    echo "Invalid comand '$COMMAND'"
    exit 1
esac
# deploy:img)
#   set -a && source env/.env && set +a   # env file import
#   if [[ -z $TAG_NAME ]]; then
#     echo "No tag name. check env"
#     exit 1
#   fi

#   docker buildx build --platform=linux/amd64 -t bcar-deploy-img .   # build for deploy
#   DOCKER_IMAGE_ID=$(docker images -q bcar-deploy-img)
#   DOCKER_IMAGE_TAG=${PRIVATE_REGISTRY_BASE_URL}/${PRIVATE_REGISTRY_PATH}:${TAG_NAME} # create additional envs
#   aws ecr get-login-password --region ${REGION} | docker login --username AWS --password-stdin ${PRIVATE_REGISTRY_BASE_URL}  # ecr login
#   docker tag ${DOCKER_IMAGE_ID} ${DOCKER_IMAGE_TAG} && docker push ${DOCKER_IMAGE_TAG}  # docker tag assign & docker image push
#   ;;
