org: wns312
app: bestcar
service: bestcar
frameworkVersion: '3'

useDotenv: true

custom:
  tableName: 'bcar-table-${sls:stage}'
  indexName: 'bcar-index-${sls:stage}'
  dotenv:
    path: env/.env

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-1
  timeout: 29
  environment:
    BCAR_TABLE: ${self:custom.tableName}
    BCAR_INDEX: ${self:custom.indexName}

functions:
  hello:
    handler: src/index.hello
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin

resources:
  Resources:
    BCarTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}

        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE

        GlobalSecondaryIndexes:
          - IndexName: ${self:custom.indexName}
            KeySchema: 
            - AttributeName: SK
              KeyType: HASH
            - AttributeName: PK
              KeyType: RANGE
            Projection:
              ProjectionType: ALL

