org: wns312
app: bestcar
service: bestcar
frameworkVersion: '3'

custom:
  tableName: 'test-table-${sls:stage}'

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-1
  timeout: 60
  environment:
    TEST_TABLE: ${self:custom.tableName}

functions:
  hello:
    handler: src/index.hello
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-plugin-typescript
  - serverless-offline

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}