org: wns312
app: bestcar
service: bestcar
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-1
  timeout: 60

functions:
  hello:
    handler: src/index.hello
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-plugin-typescript
  - serverless-offline

package:
  patterns:
    # - '!node_modules/chrome-aws-lambda/**'
    # - '!node_modules/puppeteer/.local-chromium/**'