version: '3'

services:
  crawler:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./env/.env
      - ./env/aws.env
      - ./env/prod.env
    volumes:
      - ./src:/app/src
      - ./dist:/app/dist
