service: trigger
frameworkVersion: '3'

provider:
  environment:
    JOB_DEFINITION_NAME: bcar-job-definition
    SYNC_JOB_QUEUE_NAME: bcar-job-queue
    UPLOAD_JOB_QUEUE_NAME: bcar-upload-cars-job-queue
    REGION: ap-northeast-2

  name: aws
  stage: "prod"
  runtime: nodejs16.x
  region: ap-northeast-2
  iam:
    role:
      statements:
        - Effect: Allow
          Action: "batch:SubmitJob"
          Resource: "*"

functions:
  collectDrafts:
    handler: index.collectDrafts
    events:
      - schedule: cron(0 21 * * ? *) # 아침 6시
      - schedule: cron(0 3 * * ? *)  # 정오 12시
      - schedule: cron(0 7 * * ? *)  # 오후 4시
      - schedule: cron(0 12 * * ? *) # 저녁 9시
  manageCars:
    handler: index.manageCars

plugins:
  - serverless-plugin-typescript
  - serverless-offline
