const {
  SOURCE_ADMIN_ID,
  SOURCE_ADMIN_PW,
  SOURCE_LOGIN_PAGE,
  SOURCE_MANAGE_PAGE,
  SOURCE_SEARCH_BASE,
  SOURCE_DETAIL_PAGE_BASE,
  BCAR_TABLE,
  BCAR_INDEX,
  BCAR_CATEGORY_TABLE,
  BCAR_CATEGORY_INDEX,
  NODE_ENV,
  REGION,
  JOB_DEFINITION_NAME,
  JOB_QUEUE_ARN,
  JOB_QUEUE_NAME,
  PRIVATE_REGISTRY_BASE_URL,
  PRIVATE_REGISTRY_PATH,
  TAG_NAME,
  TASK_EXECUTION_ROLE_ARN,
  GOOGLE_CLIENT_EMAIL,
  GOOGLE_PRIVATE_KEY,
  GOOGLE_ACCOUNT_SHEET_NAME,
  GOOGLE_SPREAD_SHEET_ID,
  GOOGLE_KCRURL_SHEET_NAME,
} = process.env

const envs = {
  NODE_ENV: NODE_ENV || "local",
  BCAR_TABLE: BCAR_TABLE!,
  BCAR_INDEX: BCAR_INDEX!,
  BCAR_CATEGORY_TABLE: BCAR_CATEGORY_TABLE!,
  BCAR_CATEGORY_INDEX: BCAR_CATEGORY_INDEX!,
  GOOGLE_CLIENT_EMAIL: GOOGLE_CLIENT_EMAIL!,
  GOOGLE_PRIVATE_KEY: GOOGLE_PRIVATE_KEY!.replaceAll("\\n", "\n"),
  GOOGLE_ACCOUNT_SHEET_NAME: GOOGLE_ACCOUNT_SHEET_NAME!,
  GOOGLE_KCRURL_SHEET_NAME: GOOGLE_KCRURL_SHEET_NAME!,
  GOOGLE_SPREAD_SHEET_ID: GOOGLE_SPREAD_SHEET_ID!,

  REGION: REGION!,
  JOB_DEFINITION_NAME: JOB_DEFINITION_NAME!,
  JOB_QUEUE_ARN: JOB_QUEUE_ARN!,
  JOB_QUEUE_NAME: JOB_QUEUE_NAME!,
  PRIVATE_REGISTRY_BASE_URL: PRIVATE_REGISTRY_BASE_URL!,
  PRIVATE_REGISTRY_PATH: PRIVATE_REGISTRY_PATH!,
  TAG_NAME: TAG_NAME!,
  TASK_EXECUTION_ROLE_ARN: TASK_EXECUTION_ROLE_ARN!,

  SOURCE_ADMIN_ID: SOURCE_ADMIN_ID!,
  SOURCE_ADMIN_PW: SOURCE_ADMIN_PW!,
  SOURCE_LOGIN_PAGE: SOURCE_LOGIN_PAGE!,
  SOURCE_MANAGE_PAGE: SOURCE_MANAGE_PAGE!,
  SOURCE_SEARCH_BASE: SOURCE_SEARCH_BASE!,
  SOURCE_DETAIL_PAGE_BASE: SOURCE_DETAIL_PAGE_BASE!,
}

if (!Object.values(envs).every(env => env !== undefined)) {
  throw new Error('Importing required env failed')
}

export { envs }
